CC=gcc
run=q1_a

exec: $(run)

# make run="q1_a"
q1_a: q1_a.c
	$(CC) q1_a.c -o q1_a.o
	chmod +x q1_a.o
	./q1_a.o

# make run="q1_b"
q1_b: q1_b.c
	$(CC) q1_b.c -o q1_b.o
	chmod +x q1_b.o
	./q1_b.o

# make run="q2_a"
q2_a: q2_a.c
	$(CC) q2_a.c -o q2_a.o
	chmod +x q2_a.o
	./q2_a.o

# make run="q2_b"
q2_b: q2_b.c
	$(CC) q2_b.c -o q2_b.o
	chmod +x q2_b.o
	./q2_b.o

# make run="q2_c1"
q2_c1: q2_c1.c
	$(CC) q2_c1.c -o q2_c1.o
	chmod +x q2_c1.o
	./q2_c1.o

# make run="q2_c2"
q2_c2: q2_c2.c
	$(CC) q2_c2.c -o q2_c2.o
	chmod +x q2_c2.o
	./q2_c2.o

# make run="q3"
q3: q3.c
	$(CC) q3.c -o q3.o
	chmod +x q3.o
	./q3.o

# make run="q5"
q5: q5.c
	$(CC) q5.c -o q5.o
	chmod +x q5.o
	./q5.o

clean:
	rm -rf *o
